const medicine = "Insulin"
const description = 'Lowers your blood sugar'
describe('Adding Medication to DB from Front-end', ()=>{
    it('Should add a medicine to the DB and fail if it exists', () =>{
        cy.visit('http://localhost:3000')
        cy.get('#username').type('admin')
        cy.get('#password').type('12345')
        cy.get('#submit').click()
        cy.get('#medicine').click()
        cy.get('#addmed').click()
        cy.get('form > input[type="text"]').type('Ritalin LA')
        cy.get('form > textarea[type="text"]').type(description)
        cy.get('form > button[type="submit"]').click()
        cy.contains('Medicine already exists')
    })
    it('Should fail if the name is blank',()=> {
        cy.visit('http://localhost:3000')
        cy.get('#username').type('admin')
        cy.get('#password').type('12345')
        cy.get('#submit').click()
        cy.get('#medicine').click()
        cy.get('#addmed').click()
        cy.get('form > textarea[type="text"]').type(description)
        cy.get('form > button[type="submit"]').click()
        cy.contains("Name can't be blank")
    })
    it('Should fail if the description is blank',()=> {
        cy.visit('http://localhost:3000')
        cy.get('#username').type('admin')
        cy.get('#password').type('12345')
        cy.get('#submit').click()
        cy.get('#medicine').click()
        cy.get('#addmed').click()
        cy.get('form > input[type="text"]').type('Pineapples')
        cy.get('form > button[type="submit"]').click()
        cy.contains("Description can't be blank")
    })
    it('should create a new medicine, redirect to the new page and show the new medicine', ()=>{
        cy.visit('http://localhost:3000')
        cy.get('#username').type('admin')
        cy.get('#password').type('12345')
        cy.get('#submit').click()
        cy.get('#medicine').click()
        cy.get('#addmed').click()
        cy.get('form > input[type="text"]').type('Insulin')
        cy.get('form > textarea[type="text"]').type(description)
        cy.get('form > button[type="submit"]').click()
        cy.contains('Insulin')
    })
} )